[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django-variable"
authors = [{name = "Jeisson Perez M", email = "jeissonp@gmail.com"}]
version = "0.1.0"